
CREATE TABLE IF NOT EXISTS `characters` (
  `charidentifier` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(50) NOT NULL DEFAULT '',
  `steamname` varchar(50) NOT NULL DEFAULT '',
  `group` varchar(10) DEFAULT 'user',
  `firstname` varchar(50) DEFAULT ' ',
  `lastname` varchar(50) DEFAULT ' ',
  `gender` int(11) DEFAULT 0,
  `dob` varchar(50) DEFAULT NULL,
  `skin` varchar(50) DEFAULT NULL,
  `skinComp` longtext DEFAULT '[]',
  `job` varchar(50) DEFAULT 'unemployed',
  `jobLevel` int(11) DEFAULT 1,
  `jobLevelExperience` int(11) NOT NULL DEFAULT 0,
  `clan` int(11) DEFAULT 0,
  `money` int(11) DEFAULT 0,
  `gold` int(11) DEFAULT 0,
  `donateCoins` int(11) NOT NULL DEFAULT 0,
  `healthOuter` int(4) DEFAULT 500,
  `healthInner` int(4) DEFAULT 100,
  `staminaOuter` int(4) DEFAULT 100,
  `staminaInner` int(4) DEFAULT 100,
  `coords` varchar(75) DEFAULT '{}',
  `warnings` tinyint(1) DEFAULT NULL,
  `banned` tinyint(1) DEFAULT 0,
  `bannedReason` longtext DEFAULT 'N/A',
  `isdead` tinyint(1) DEFAULT 0,
  `hours` float NOT NULL DEFAULT 0,
  PRIMARY KEY (`charidentifier`),
  UNIQUE KEY `charidentifier` (`charidentifier`),
  KEY `identifier` (`identifier`)
) ENGINE=InnoDB AUTO_INCREMENT=235 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
